version: '2'
services:
    trade-app:
        image: trade
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://trade-mysql:3306/trade?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trade-mysql:
        extends:
            file: mysql.yml
            service: trade-mysql
